spring:
  application.name: configuration_server
  main:
    banner-mode: off
  cloud:
    config:
      enabled: true
      server:
        git:
          defaultLabel: main
          uri: https://github.com/Diegodenac/configserver.git
server:
  port: 8888